### ISSUE TITLE
Create "hello world" website

### ISSUE THREAD

**Issue by BenMatase** [BenMatase/EnergyHill#76]

**Comment by DTV96Calibre** [comment]
What functionality are we looking for in this website? I'm working out a hello world page demonstrating accessing a MySQL database using mysqljs.

**Comment by tomficcadenti** [comment]
Will be explained in class (t-minus 10 minutes)

**Comment by BenMatase** [comment]
We determined that Spring/Vaadin isn't going to be best for us at this point so we are making the website in raw html/css/js
